### ISSUE TITLE
Add support for ZFSoL

### ISSUE THREAD

**Issue by chjohnst** [allanjude/zxfer#10]

**Comment by allanjude** [comment]
What problems are there with this script and ZFSoL?
I am not a linux user, but if you can point out some errors or suggest changes, I'd be happy to accept them

**Comment by chjohnst** [comment]
I am going to test this out today on my CentOS 6.5 host, see if any updates
need to be made.  Was putting this in as a placeholder to help certify it.

**Comment by sl6xx** [comment]
I'm testing zxfer on my two VMs running CentOS 7.2.  I got this error when trying replicate a pool: 

[root@zfslive ~]# zxfer -dFkPv -T root@192.168.88.16 -R tank pool/zfslive
/usr/local/sbin/zxfer: line 693: syntax error near unexpected token `fi'
/usr/local/sbin/zxfer: line 693: `  fi'

**Comment by allanjude** [comment]
I thought I fixed that. What version do you have? Make sure it is 1.1.6

**Comment by sl6xx** [comment]
it is the master branch that has this problem.  1.1.6 works fine.

**Comment by allanjude** [comment]
I forgot to push master after creating the tag. Master is correct as of 2 hours ago
