### ISSUE TITLE
adding mbuffer optional functionality - feasibility check

### ISSUE THREAD

**Issue by petr-fischer** [allanjude/zxfer#44]
Hello! Is possible to add mbuffer optional functionality (I can do it and send push request). Look, this is typical zxfer call:

` $LZFS send -i "$copyprev" "$copysrc" | $RZFS receive $option_F "$copydest";`

So we can add this to every send/receive call:

` $LZFS send -i "$copyprev" "$copysrc" |  $SOMETHING  | $RZFS receive $option_F "$copydest";`

It can be optional: if we want mbuffer, we set `SOMETHING` to `mbuffer` and if we don't want mbuffer, we can set `SOMETHING` simply to `cat`.

Do you have any comments on it? Is that feasible? Shall I try it? Thanks!

**Comment by allanjude** [comment]
You shouldn't need to modify zxfer to do this, I added this feature already:

-D 'mbuffer ...settings...'

It also replaces %%size%% in the command with the estimated size of the send stream, so you can get a progress bar from whatever tool you use (clpbar, pv, dpv, mbuffer, etc)

**Comment by allanjude** [comment]
You can find it in the code as zfs send | $PROGRESS_DIALOG | zfs recv

**Comment by petr-fischer** [comment]
I see it! Thanks.
