### ISSUE TITLE
strange readonly filesystem_count error

### ISSUE THREAD

**Issue by memnochproxy** [allanjude/zxfer#49]
I've tried various combinations of zfs allow, sudo and as root. It appears that the destination filesystem doesn't want to be created. Hints on what I should look at next?

 > zfs get readonly fs2pool/mail3-bu/spool
NAME                    PROPERTY  VALUE   SOURCE
fs2pool/mail3-bu/spool  readonly  off     default

+ /usr/local/bin/zxfer -dFkv -g700 -O ctbu@mail3d -R mail3spool1/spool/mail fs2pool/mail3-bu/spool
Checking grandfather status of all snapshots marked for deletion...
Grandfather check passed.
Creating destination filesystem "fs2pool/mail3-bu/spool/mail" with specified properties.
cannot create 'fs2pool/mail3-bu/spool/mail': 'filesystem_count' is readonly
Error when creating destination filesystem.

**Comment by kpfleming** [comment]
zxfer is trying to set a property called `filesystem_count` which can't be set. Which version of zxfer are you using and what are the source and destination operating systems/versions?

**Comment by memnochproxy** [comment]
cd /usr/local/src/zxfer
 $ git show
commit aa6ac974cc15b4bc06b6f02598e19746c2537230
Merge: 1893890 895e892
Author: Allan Jude <github@shellfusion.ca>
Date:   Wed Dec 19 12:58:59 2018 -0500

    Merge pull request #47 from matsimon/new-readonly-attributes

    Declare new readonly properties: createtxg and guid

 $ cat /sys/module/spl/version
0.8.0-rc3
$ zfs get version fs2pool
5
cd /usr/local/src/zfs
 $ git show
commit 07237a7bc1eab62d8bb2bb7b4abafe7a2fd3a482
Author: John Wren Kennedy <jwk404@gmail.com>
Date:   Fri Feb 15 13:45:46 2019 -0700

**Comment by memnochproxy** [comment]
and on sending system,
 $ cat /sys/module/spl/version
0.7.12-1
 $ rpm -qi zfs
Name        : zfs
Version     : 0.7.12
Release     : 1.el7_6
Architecture: x86_64
Install Date: Wed 06 Feb 2019 09:59:01 AM PST

**Comment by allanjude** [comment]
the filesystem_count property is always read only, it is purely informational, like 'compressratio' etc, you can't change it. It is the count of child datasets, related to the filesystem_limit property, that lets you limit how many child datasets someone can create when you delegate a filesystem to them.

It should be on the readonly_properties list, and somehow is not, I'll get that fixed up.
